### ISSUE TITLE
How to download video via nitter

### ISSUE THREAD

**Issue by treble2019** [zedeus/nitter#153]
How does one download this:
https://nitter.snopyta.org/cyrildiagne/status/1256916982764646402#m

Right-Click does not show Save As
(Sorry to ask this here)

**Comment by treble2019** [comment]
Open the browser's Dev Tools  and get the m3u8

`youtube-dl   -f mp4  "actual nitter with .m3u8" `

**Comment by zedeus** [comment]
I tried figuring out hot to enable downloads with hls.js but only garbled data came out. Maybe I'll try again some time, till then `youtube-dl` works fine and has a pending PR for nitter.

**Comment by treble2019** [comment]
(In principle this is not urgent, for me at least).

> till then youtube-dl works fine and has a pending PR for nitter.

 youtube-dl works only with **Open the browser's Dev Tools and get the m3u8**




Not directly:

```

youtube-dl --verbose "https://nitter.net/cyrildiagne/status/1256916982764646402"
[debug] System config: []
[debug] User config: [u'-o', u'./%(title)s.%(ext)s', u'--no-mtime', u'--max-downloads=5', u'--restrict-filenames']
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://nitter.net/cyrildiagne/status/1256916982764646402']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.05.03
[debug] Python version 2.7.12 (CPython) - Linux-4.15.0-91-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.15, ffprobe 2.8.15, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 1256916982764646402: Requesting header
WARNING: Could not send HEAD request to https://nitter.net/cyrildiagne/status/1256916982764646402: HTTP Error 404: Not Found
[generic] 1256916982764646402: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] 1256916982764646402: Extracting information
ERROR: Unsupported URL: https://nitter.net/cyrildiagne/status/1256916982764646402
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 3370, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://nitter.net/cyrildiagne/status/1256916982764646402

```

**Comment by zedeus** [comment]
Yeah, I meant it works fine if you replace nitter.net with twitter or manually copy the m3u8

**Comment by treble2019** [comment]
Now understood. (BTW, many thanks for your great work -very much appreciated)

**Comment by B0pol** [comment]
Use [youtube-dlc](https://github.com/blackjack4494/yt-dlc/)
