### ISSUE TITLE
Doesn't scraping on non-private account

### ISSUE THREAD

**Issue by Mertozturkk** [zedeus/nitter#991]
```
2023-08-25 13:11:50.493 | INFO     | nitter_scraper.nitter:_get_client:31 - Docker connection successful.
2023-08-25 13:11:51.834 | INFO     | nitter_scraper.nitter:start:155 - Running container heuristic_mclaren 6982f296dd.
2023-08-25 13:11:51.985 | INFO     | nitter_scraper.nitter:stop:159 - Stopping container heuristic_mclaren 6982f296dd.
2023-08-25 13:11:57.157 | INFO     | nitter_scraper.nitter:stop:162 - Container heuristic_mclaren 6982f296dd Destroyed.
Traceback (most recent call last):
  File "/home/admin/test.py", line 6, in <module>
    profile = nitter.get_profile("elonmusk")
  File "/home/admin/.local/lib/python3.9/site-packages/nitter_scraper/nitter.py", line 114, in get_profile
    return get_profile(username=username, not_found_ok=not_found_ok, address=self.address)
  File "/home/admin/.local/lib/python3.9/site-packages/nitter_scraper/profile.py", line 207, in get_profile
    raise ValueError(f'Oops! Either "{username}" does not exist or is private.')
ValueError: Oops! Either "elonmusk" does not exist or is private.

```

where could i go wrong ?

**Comment by zedeus** [comment]
Are you running your instance?

**Comment by Mertozturkk** [comment]
yes i installed it with docker compose on my own debian server

**Comment by zedeus** [comment]
Nitter is broken right now for scraping purposes as you need a lot of guest accounts. See #983

**Comment by posornio** [comment]
any updates? I have this exact problem

**Comment by zedeus** [comment]
https://github.com/zedeus/nitter/wiki/Guest-Account-Branch-Deployment
